// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkHCFZq-FPrxV3nAFu4fiLOPEqeYJA6I',
    appId: '1:969205944430:web:bb1aab1755da3f05a3d67f',
    messagingSenderId: '969205944430',
    projectId: 'saidee-app',
    authDomain: 'saidee-app.firebaseapp.com',
    storageBucket: 'saidee-app.firebasestorage.app',
    measurementId: 'G-WXXC2D49HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2DBjonukfNRuWR0YUSbdwUXV94HqGhc',
    appId: '1:969205944430:android:8d142259fbd00a3fa3d67f',
    messagingSenderId: '969205944430',
    projectId: 'saidee-app',
    storageBucket: 'saidee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapqC22ZZmCCKogoWXFaSO-cB5ilFUB9Q',
    appId: '1:969205944430:ios:938adf1ede8e10bda3d67f',
    messagingSenderId: '969205944430',
    projectId: 'saidee-app',
    storageBucket: 'saidee-app.firebasestorage.app',
    iosClientId: '969205944430-a78ppnbkkodq19kto1jmrqpqjn3dovhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.saideeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAapqC22ZZmCCKogoWXFaSO-cB5ilFUB9Q',
    appId: '1:969205944430:ios:938adf1ede8e10bda3d67f',
    messagingSenderId: '969205944430',
    projectId: 'saidee-app',
    storageBucket: 'saidee-app.firebasestorage.app',
    iosClientId: '969205944430-a78ppnbkkodq19kto1jmrqpqjn3dovhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.saideeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKkHCFZq-FPrxV3nAFu4fiLOPEqeYJA6I',
    appId: '1:969205944430:web:f5230969e8151aafa3d67f',
    messagingSenderId: '969205944430',
    projectId: 'saidee-app',
    authDomain: 'saidee-app.firebaseapp.com',
    storageBucket: 'saidee-app.firebasestorage.app',
    measurementId: 'G-JE9B9SXMX7',
  );
}
